# -*- coding: utf-8 -*-
"""assignment_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qnk1El4lnXc4jx8qWueIg54PzmCo0CG7

# CPSC 393 -- Assignment 03
"""

# Imports

import numpy as np
import pandas as pd
import os

from google.colab import files

import matplotlib.pyplot as plt
from plotnine import *
from PIL import Image

import tensorflow as tf
from tensorflow import keras

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import regularizers
from tensorflow.keras import layers, models, Model
from tensorflow.keras.preprocessing import image_dataset_from_directory


from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications import VGG16

import warnings
warnings.filterwarnings('ignore')

"""#  Data Preprocessing"""

# Claude Utilized to Debug Data Importing Issues (cited in README) (1)

# Upload kaggle.json
print("Upload your kaggle.json:")
uploaded = files.upload()

# Setup Kaggle
!mkdir -p ~/.kaggle
!mv kaggle*.json ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json
!pip install -q kaggle

# Download the Dataset
print("\nDownloading fruit dataset!")
!kaggle datasets download -d kritikseth/fruit-and-vegetable-image-recognition

# Unzip Data
print("\nExtracting data...")
!unzip -q fruit-and-vegetable-image-recognition.zip -d /content/fruits

# Ensure Structure is Correct
print("\nChecking data structure...")
!ls /content/fruits

# Find Paths
contents = os.listdir('/content/fruits')
print(f"Contents: {contents}")

# Parse through Folders, Extract train, test, val paths
if 'train' in contents:
    train_path = '/content/fruits/train'
    val_path = '/content/fruits/validation'
    test_path = '/content/fruits/test'
elif len(contents) == 1 and os.path.isdir(f'/content/fruits/{contents[0]}'):
    base = f'/content/fruits/{contents[0]}'
    train_path = f'{base}/train'
    val_path = f'{base}/validation'
    test_path = f'{base}/test'
else:
    # Check what's actually there
    for item in contents:
        item_path = f'/content/fruits/{item}'
        if os.path.isdir(item_path):
            print(f"\nContents of {item}:")
            print(os.listdir(item_path)[:10])

# Image Generators for Train, Val, and Test Data

train_gen = ImageDataGenerator(
    rescale=1./255,
).flow_from_directory(
    train_path,
    target_size=(128, 128),
    batch_size=32,
    class_mode=None,
    #shuffle=True,
)


val_gen = ImageDataGenerator(
    rescale=1./255
).flow_from_directory(
    val_path,
    target_size=(128, 128),
    batch_size=32,
    class_mode=None,
)


test_gen = ImageDataGenerator(
    rescale=1./255
).flow_from_directory(
    test_path,
    target_size=(128, 128),
    batch_size=32,
    class_mode=None,
)

print(f"\nFruit Dataset Downloaded Successfully!")
print(f"Training: {train_gen.samples} images, {train_gen.num_classes} classes")
print(f"Validation: {val_gen.samples} images")
print(f"Test: {test_gen.samples} images")

# Convert Generators to Numpy Arrays
print("\nConverting generators to arrays...")

# Claude Utilized for Data Preprocessing (cited in README) (2)
def generator_to_arrays(generator, num_samples, has_labels=True):
    images_list = []
    labels_list = []
    samples_collected = 0

    for batch in generator:
        if has_labels:
            images, labels = batch
        else:
            images = batch
            labels = batch

        images_list.append(images)
        labels_list.append(labels)
        samples_collected += len(images)
        if samples_collected >= num_samples:
            break

    return np.vstack(images_list)[:num_samples], np.vstack(labels_list)[:num_samples]

X_train, y_train = generator_to_arrays(train_gen, train_gen.samples, has_labels=False)
X_val, y_val = generator_to_arrays(val_gen, val_gen.samples, has_labels=False)
X_test, y_test = generator_to_arrays(test_gen, test_gen.samples, has_labels=False)

print(f"Data Format Check:")
print(f"  X_train shape: {X_train.shape}")
print(f"  X_val shape: {X_val.shape}")
print(f"  X_test shape: {X_test.shape}")
print(f"  Data type: {X_train.dtype}")
print(f"  Value range: [{X_train.min():.2f}, {X_train.max():.2f}]")

# Set the Noise Factor
noise_factor = 0.4

# Create Noisy Data
X_train_noisy = X_train + noise_factor * np.random.normal(loc=0.0, scale=1.0, size=X_train.shape)
X_val_noisy = X_val + noise_factor * np.random.normal(loc=0.0, scale=1.0, size=X_val.shape)
X_test_noisy = X_test + noise_factor * np.random.normal(loc=0.0, scale=1.0, size=X_test.shape)

# Transform Noisy Data
X_train_noisy = np.clip(X_train_noisy, 0., 1.)
X_val_noisy = np.clip(X_val_noisy, 0., 1.)
X_test_noisy = np.clip(X_test_noisy, 0., 1.)

"""# Exploratory Data Analysis"""

# Show 10 Random Images from Dataset
dataset = image_dataset_from_directory('fruits/train/', image_size=(128,128))
class_names = dataset.class_names

plt.figure(figsize=(15,6))
for images, labels in dataset.take(1):
    for i in range(10):
        plt.subplot(2, 5, i+1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(class_names[labels[i]])
        plt.axis("off")

# Show Number of Images for Each Type in Train Folder
class_counts = [len(os.listdir(os.path.join('fruits/train', c))) for c in class_names]


plt.figure(figsize=(45, 10))
plt.bar(class_names, class_counts, color="purple")
plt.title("Number of Images per Class")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

"""# Deep Convolutional Autoencoder"""

##### Build the Deep Convolutional Autoencoder (Base Model)
print("\nBuilding Deep Convolutional Autoencoder...")

# Set Regularization Parameters
l2_reg = 0.001  # L2 regularization
dropout_rate = 0.2  # Dropout

# Create the Input Image
input_img = tf.keras.layers.Input(shape=(128, 128, 3))

##### Encoder

# Conv Layer 1
x = tf.keras.layers.Conv2D(32, (3, 3), activation="relu", padding="same",
                           kernel_regularizer=regularizers.l2(l2_reg))(input_img)
x = tf.keras.layers.BatchNormalization()(x)

# Max Pool 1
x = tf.keras.layers.MaxPooling2D((2, 2), padding="same")(x)
x = tf.keras.layers.Dropout(dropout_rate)(x)

# Conv Layer 2
x = tf.keras.layers.Conv2D(64, (3, 3), activation="relu", padding="same",
                           kernel_regularizer=regularizers.l2(l2_reg))(x)
x = tf.keras.layers.BatchNormalization()(x)

# Conv Layer 3
x = tf.keras.layers.Conv2D(64, (3, 3), activation="relu", padding="same",
                           kernel_regularizer=regularizers.l2(l2_reg))(x)

# Max Pool 2
x = tf.keras.layers.MaxPooling2D((2, 2), padding="same")(x)
x = tf.keras.layers.Dropout(dropout_rate)(x)

# Conv Layer 4
x = tf.keras.layers.Conv2D(128, (3, 3), activation="relu", padding="same",
                           kernel_regularizer=regularizers.l2(l2_reg))(x)
x = tf.keras.layers.BatchNormalization()(x)

# Conv Layer 5
x = tf.keras.layers.Conv2D(128, (3, 3), activation="relu", padding="same",
                           kernel_regularizer=regularizers.l2(l2_reg))(x)

# Max Pool 3
encoded = tf.keras.layers.MaxPooling2D((2, 2), padding="same")(x)


#### Decoder

# Conv Layer 6
x = tf.keras.layers.Conv2D(128, (3, 3), activation="relu", padding="same",
                           kernel_regularizer=regularizers.l2(l2_reg))(encoded)
x = tf.keras.layers.BatchNormalization()(x)

# Up Sampling 1
x = tf.keras.layers.UpSampling2D((2, 2))(x)

# Conv Layer 7
x = tf.keras.layers.Conv2D(128, (3, 3), activation="relu", padding="same",
                           kernel_regularizer=regularizers.l2(l2_reg))(x)
x = tf.keras.layers.BatchNormalization()(x)

# Conv Layer 8
x = tf.keras.layers.Conv2D(64, (3, 3), activation="relu", padding="same",
                           kernel_regularizer=regularizers.l2(l2_reg))(x)

# Up Sampling 2
x = tf.keras.layers.UpSampling2D((2, 2))(x)

# Conv Layer 9
x = tf.keras.layers.Conv2D(64, (3, 3), activation="relu", padding="same",
                           kernel_regularizer=regularizers.l2(l2_reg))(x)
x = tf.keras.layers.BatchNormalization()(x)

# Conv Layer 10
x = tf.keras.layers.Conv2D(32, (3, 3), activation="relu", padding="same",
                           kernel_regularizer=regularizers.l2(l2_reg))(x)

# Up Sampling 3
x = tf.keras.layers.UpSampling2D((2, 2))(x)


# Conv Layer 11 (Output Layer)
decoded = tf.keras.layers.Conv2D(3, (3, 3), activation="sigmoid", padding="same")(x)


# Create the Autoencoder
denoising_autoencoder = tf.keras.Model(input_img, decoded, name='denoising_autoencoder')

# Model Summary
denoising_autoencoder.summary()

"""# Train the Base Model"""

# Compile the Autoencoder with Metrics
denoising_autoencoder.compile(
    optimizer= tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss= 'mse',
    metrics= ['mae', 'mse']
)

print("\nTraining model...")

# Define Earlystopping
early_stop = keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True,
    verbose=1
)

# Learning Rate
reduce_lr = keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=3,
    verbose=1,
    min_lr=1e-6
)

# Fit the Model
history = denoising_autoencoder.fit(
    X_train_noisy, X_train,
    epochs=5,
    batch_size=16,
    shuffle=True,
    validation_data=(X_val_noisy, X_val),
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

print("Training complete!")


# Print Metrics
final_epoch = len(history.history['loss'])

print(f"\nFinal Epoch {final_epoch} Results:")
print(f"\nTraining Metrics:")
print(f"  MAE: {history.history['mae'][-1]:.4f}")
print(f"  MSE: {history.history['mse'][-1]:.4f}")

print(f"\nValidation Metrics:")
print(f"  MAE: {history.history['val_mae'][-1]:.4f}")
print(f"  MSE: {history.history['val_mse'][-1]:.4f}")

# Plot Training and Validation History
fig, axes = plt.subplots(1, 3, figsize=(18, 4))

# MAE
axes[0].plot(history.history['mae'], label='Train MAE', marker='o')
axes[0].plot(history.history['val_mae'], label='Val MAE', marker='s')
axes[0].set_title('Mean Absolute Error')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('MAE')
axes[0].legend()
axes[0].grid(True)

# MSE
axes[1].plot(history.history['mse'], label='Train MSE', marker='o')
axes[1].plot(history.history['val_mse'], label='Val MSE', marker='s')
axes[1].set_title('Mean Squared Error')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('MSE')
axes[1].legend()
axes[1].grid(True)

plt.tight_layout()
plt.show()

"""# Convolutional Autoencoder Denoised Images"""

# Base Model Generates Denoised Images
print("\nGenerating denoised images...")

X_test_denoised = denoising_autoencoder.predict(X_test_noisy)

# ChatGPT generated this function (cited in README) (3)
# Plot Input, Noisy, and Denoised Images
def plot_reconstructions(input_images, noisy_input, ae_output, n=10):
    plt.figure(figsize=(18, 6))
    for i in range(n):

        # Noisy
        ax = plt.subplot(3, n, i + 1)
        plt.imshow(noisy_input[i])
        if i == 0:
            plt.title("Noisy", fontsize=12)
        plt.axis('off')

        # Clean
        ax = plt.subplot(3, n, i + 1 + n)
        plt.imshow(input_images[i])
        if i == 0:
            plt.title("Clean", fontsize=12)
        plt.axis('off')

        # Denoised
        ax = plt.subplot(3, n, i + 1 + 2 * n)
        plt.imshow(ae_output[i])
        if i == 0:
            plt.title("Denoised", fontsize=12)
        plt.axis('off')

    plt.suptitle('Denoising Autoencoder Results on Fruit and Vegetable Images', fontsize=14, y=1.02)
    plt.tight_layout()
    plt.show()

# Display results
plot_reconstructions(X_test, X_test_noisy, X_test_denoised, n=10)

# Evaluate the Reconstructions
print("\n Test Set Evaluation:")
test_results = denoising_autoencoder.evaluate(X_test_noisy, X_test, verbose=0)
print(f"  Test MAE: {test_results[1]:.4f}")
print(f"  Test MSE: {test_results[2]:.4f}")

# ChatGPT generated this function (cited in README) (5)
# Calculate the Improvement
noisy_mse = np.mean((X_test - X_test_noisy) ** 2)
denoised_mse = np.mean((X_test - X_test_denoised) ** 2)
improvement = ((noisy_mse - denoised_mse) / noisy_mse) * 100

print(f"\n Denoising Performance:")
print(f"  MSE (Clean vs Noisy): {noisy_mse:.4f}")
print(f"  MSE (Clean vs Denoised): {denoised_mse:.4f}")
print(f"  Improvement: {improvement:.2f}%")

"""# Autoencoder Worst 3"""

# Compute the Reconstruction Error per-image
reconstruction_errors = np.mean((X_test - X_test_denoised)**2, axis=(1,2,3))

# ChatGPT generated this function (cited in README) (4)
# Get 3 Images with Highest Error
worst_3 = np.argsort(reconstruction_errors)[-3:]
print("Worst images:", worst_3)

n = 3
plt.figure(figsize=(15, 6))

for i, idx in enumerate(worst_3):
    # Noisy
    ax = plt.subplot(3, n, i + 1)
    plt.imshow(X_test_noisy[idx])
    plt.title(f"Noisy (err={reconstruction_errors[idx]:.4f})")
    plt.axis("off")

    # Denoised
    ax = plt.subplot(3, n, i + 1 + n)
    plt.imshow(X_test_denoised[idx])
    plt.title("Denoised Output")
    plt.axis("off")

    # Clean
    ax = plt.subplot(3, n, i + 1 + 2*n)
    plt.imshow(X_test[idx])
    plt.title("Original Clean")
    plt.axis("off")

"""# ###############################################

# Transfer Learning Autoencoder
"""

##### Build the Transfer Learning Autoencoder
print("\nBuilding Transfer Learning Autoencoder...")

# Set Regularization Parameters

l2_reg = 0.001  # L2 regularization
dropout_rate = 0.2  # Dropout

print("\nLoading pretrained VGG16 Model...")

# Load Pretrained Encoder
base_model = VGG16(
    include_top=False,
    input_shape=(128, 128, 3)
)

# Freeze the Base Model
base_model.trainable = False
print(f"Encoder output shape: {base_model.output.shape}")

# Get Encoder Output
x = base_model.output


##### New Decoder Head

# Conv Layer 1
x = tf.keras.layers.Conv2D(512, (3, 3), activation='relu', padding='same')(x)
x = tf.keras.layers.BatchNormalization()(x)

# Up Sampling 1
x = tf.keras.layers.UpSampling2D((2, 2))(x)

# Conv Layer 2
x = tf.keras.layers.Conv2D(256, (3, 3), activation='relu', padding='same')(x)
x = tf.keras.layers.BatchNormalization()(x)

# Up Sampling 2
x = tf.keras.layers.UpSampling2D((2, 2))(x)

# Conv Layer 3
x = tf.keras.layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x)
x = tf.keras.layers.BatchNormalization()(x)

# Up Sampling 3
x = tf.keras.layers.UpSampling2D((2, 2))(x)

# Conv Layer 4
x = tf.keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x)
x = tf.keras.layers.BatchNormalization()(x)

# Up Sampling 4
x = tf.keras.layers.UpSampling2D((2, 2))(x)

# Conv Layer 5
x = tf.keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same')(x)
x = tf.keras.layers.BatchNormalization()(x)

# Up Sampling 5
x = tf.keras.layers.UpSampling2D((2, 2))(x)

# Conv 6 (Output Layer)
decoded_output = tf.keras.layers.Conv2D(3, (3, 3), activation='sigmoid', padding='same')(x)


# Create the TL Autoencoder
transfer_autoencoder = Model(
    inputs=base_model.input,
    outputs=decoded_output,
    name='transfer_learning_autoencoder'
)

print("\nTransfer Learning Autoencoder Created!")

# Model Summary
transfer_autoencoder.summary()

"""# Train TL Autoencoder"""

# Compile Model with Metrics
transfer_autoencoder.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='mse',
    metrics=['mae', 'mse']
)

# Train the Model
print("\nTraining Transfer Learning model...")

# Define Early Stopping
early_stop_tl = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True,
    verbose=1
)

# Learning Rate
reduce_lr_tl = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=2,
    verbose=1,
    min_lr=1e-6
)

# Fit the Model
history_tl = transfer_autoencoder.fit(
    X_train_noisy, X_train,
    validation_data=(X_val_noisy, X_val),
    epochs=5,
    batch_size=16,
    shuffle=True,
    callbacks=[early_stop_tl, reduce_lr_tl],
    verbose=1
)

print("\nTraining complete!")

# Print Metrics
final_epoch = len(history_tl.history['loss'])

print(f"\nEpoch {final_epoch} Results:")

print(f"\nTraining Metrics:")
print(f"  MAE: {history_tl.history['mae'][-1]:.4f}")
print(f"  MSE: {history_tl.history['mse'][-1]:.4f}")

print(f"\nValidation Metrics:")
print(f"  MAE: {history_tl.history['val_mae'][-1]:.4f}")
print(f"  MSE: {history_tl.history['val_mse'][-1]:.4f}")

# Plot Training and Validation History
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# MAE
axes[0].plot(history_tl.history['mae'], label='Train MAE', marker='o')
axes[0].plot(history_tl.history['val_mae'], label='Val MAE', marker='s')
axes[0].set_title('Mean Absolute Error')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('MAE')
axes[0].legend()
axes[0].grid(True)

# MSE
axes[1].plot(history_tl.history['mse'], label='Train MSE', marker='o')
axes[1].plot(history_tl.history['val_mse'], label='Val MSE', marker='s')
axes[1].set_title('Mean Squared Error')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('MSE')
axes[1].legend()
axes[1].grid(True)

plt.tight_layout()
plt.show()

"""# TL Autoencoder Denoised Images"""

# TL Model Generates Denoised Images
print("\nGenerating denoised images...")

X_test_denoised = transfer_autoencoder.predict(X_test_noisy)

# ChatGPT generated this function (cited in README) (3)
# Plot Input, Noisy, and Denoised Images
def plot_reconstructions(input_images, noisy_input, ae_output, n=10):
    plt.figure(figsize=(18, 6))
    for i in range(n):

        # Noisy
        ax = plt.subplot(3, n, i + 1)
        plt.imshow(noisy_input[i])
        if i == 0:
            plt.title("Noisy", fontsize=12)
        plt.axis('off')

        # Clean
        ax = plt.subplot(3, n, i + 1 + n)
        plt.imshow(input_images[i])
        if i == 0:
            plt.title("Clean", fontsize=12)
        plt.axis('off')

        # Denoised
        ax = plt.subplot(3, n, i + 1 + 2 * n)
        plt.imshow(ae_output[i])
        if i == 0:
            plt.title("Denoised", fontsize=12)
        plt.axis('off')

    plt.suptitle('Transfer Learning Denoising Autoencoder Results on Fruit and Vegetable Images', fontsize=14, y=1.02)
    plt.tight_layout()
    plt.show()

# Display results
plot_reconstructions(X_test, X_test_noisy, X_test_denoised, n=10)

# Evaluate the Reconstructions
print("\n Test Set Evaluation:")
test_results = transfer_autoencoder.evaluate(X_test_noisy, X_test, verbose=0)
print(f"  Test MAE: {test_results[1]:.4f}")
print(f"  Test MSE: {test_results[2]:.4f}")

# ChatGPT generated this function (cited in README) (5)
# Calculate the Improvement
noisy_mse = np.mean((X_test - X_test_noisy) ** 2)
denoised_mse = np.mean((X_test - X_test_denoised) ** 2)
improvement = ((noisy_mse - denoised_mse) / noisy_mse) * 100

print(f"\n Denoising Performance:")
print(f"  MSE (Clean vs Noisy): {noisy_mse:.4f}")
print(f"  MSE (Clean vs Denoised): {denoised_mse:.4f}")
print(f"  Improvement: {improvement:.2f}%")

"""# Transfer Learning Worst 3"""

# Compute the Reconstruction Error per-image
reconstruction_errors = np.mean((X_test - X_test_denoised)**2, axis=(1,2,3))

# ChatGPT generated this function (cited in README) (4)
# Get 3 Images with Highest Error
worst_3 = np.argsort(reconstruction_errors)[-3:]
print("Worst images:", worst_3)

n = 3
plt.figure(figsize=(15, 6))

for i, idx in enumerate(worst_3):
    # Noisy
    ax = plt.subplot(3, n, i + 1)
    plt.imshow(X_test_noisy[idx])
    plt.title(f"Noisy (err={reconstruction_errors[idx]:.4f})")
    plt.axis("off")

    # Denoised
    ax = plt.subplot(3, n, i + 1 + n)
    plt.imshow(X_test_denoised[idx])
    plt.title("Denoised Output")
    plt.axis("off")

    # Clean
    ax = plt.subplot(3, n, i + 1 + 2*n)
    plt.imshow(X_test[idx])
    plt.title("Original Clean")
    plt.axis("off")